import type {
  ActivityItem,
  Artist,
  Fan,
  Metrics,
  MoneyEntry,
  Release,
  Show,
  TeamMember,
} from "@/lib/types";

export const ARTIST_ID = "artist_deja_vu";

export const artist: Artist = {
  id: ARTIST_ID,
  slug: "dejavu504",
  name: "Deja Vu 504",
  hometown: "New Orleans, LA",
  basedIn: "New Orleans",
  genre: "Bounce · rap",
  photo: "/artist/portrait.jpg",
  avatar: "/artist/avatar.jpg",
  photos: [
    "/artist/portrait.jpg",
    "/artist/press.jpg",
    "/artist/lifestyle.jpg",
    "/artist/stage.jpg",
    "/artist/street.jpg",
  ],
  shortBio: "New Orleans. Slime Princess. 504.",
  bio: "Deja Vu 504 is a New Orleans bounce and rap artist known as the Slime Princess. She raps from struggle, loyalty, and the rooms that raised her — with a fanbase that tells her they felt that. Independent, 163K strong on Instagram, and done building an audience she cannot text back.",
  bookingEmail: "dejavu504bookings@gmail.com",
  bookingPhone: "(504) 555-0140",
  pressEmail: "dejavu504bookings@gmail.com",
  welcomeText:
    "Yo, it's Deja Vu 504. Appreciate you tapping in. You're officially part of the inner circle. New music, shows, and exclusive drops land here first.",
  instagram: "https://instagram.com/dejavu504",
  tiktok: "https://tiktok.com/@dejavu504",
  twitter: "https://www.threads.net/@dejavu504",
  spotify: "https://open.spotify.com/artist/31FeTRg0UrwKHhHREE6ige",
  apple: "https://music.apple.com/us/artist/deja-vu-504/1438031169",
  youtube: "https://youtube.com/@dejavulivetv",
  website: "https://instagram.com/dejavu504",
};

export const metrics: Metrics = {
  totalFans: 1247,
  phones: 941,
  emails: 732,
  newThisWeek: 83,
  signupsByDay: [7, 9, 11, 14, 5, 37, 0],
};

function ev(
  id: string,
  date: string,
  type: Fan["engagement"][number]["type"],
  label: string,
): Fan["engagement"][number] {
  return { id, date, type, label };
}

export const fans: Fan[] = [
  {
    id: "fan_keisha",
    artistId: ARTIST_ID,
    firstName: "Keisha",
    lastName: "Williams",
    phone: "5045550142",
    email: "keisha.w@gmail.com",
    city: "New Orleans",
    favoriteSong: "Nobody",
    birthday: "1998-04-12",
    joinedAt: "2026-08-24T23:41:00",
    source: "Live show",
    tags: ["Superfan", "New Orleans", "Show attendee"],
    notes: "Front row at Republic NOLA. Knew every word.",
    lastContactedAt: "",
    fromLastShow: true,
    engagement: [
      ev("e1", "2026-08-24T23:41:00", "signup", "Joined at Republic NOLA"),
      ev("e2", "2026-08-24T23:44:00", "show", "Scanned QR after encore"),
    ],
  },
  {
    id: "fan_marcus",
    artistId: ARTIST_ID,
    firstName: "Marcus",
    lastName: "Johnson",
    phone: "4045550188",
    email: "mj.johnson@icloud.com",
    city: "Atlanta",
    favoriteSong: "Ratchet",
    birthday: "1994-11-02",
    joinedAt: "2026-06-03T14:12:00",
    source: "Instagram",
    tags: ["VIP", "Atlanta", "Merch buyer"],
    notes: "Bought the black tee + hoodie. Wants guest list Saturday.",
    lastContactedAt: "2026-08-18T10:00:00",
    engagement: [
      ev("e3", "2026-06-03T14:12:00", "signup", "Came from IG story"),
      ev("e4", "2026-07-18T21:10:00", "show", "The Loft, Atlanta"),
      ev("e5", "2026-07-20T12:00:00", "merch", "Bought hoodie"),
      ev("e6", "2026-08-18T10:00:00", "text", "Asked about Saturday tickets"),
    ],
  },
  {
    id: "fan_aaliyah",
    artistId: ARTIST_ID,
    firstName: "Aaliyah",
    lastName: "Brooks",
    phone: "7135550160",
    email: "aaliyahb@yahoo.com",
    city: "Houston",
    favoriteSong: "Pretty Gremlin",
    birthday: "2001-01-19",
    joinedAt: "2026-08-08T22:05:00",
    source: "TikTok",
    tags: ["Houston", "Superfan"],
    notes: "Stitched the Pretty Gremlin clip. 80k views.",
    lastContactedAt: "2026-08-09T09:30:00",
    engagement: [
      ev("e7", "2026-08-08T22:05:00", "signup", "TikTok bio link"),
      ev("e8", "2026-08-08T23:00:00", "show", "House of Blues Houston"),
      ev("e9", "2026-08-09T09:30:00", "text", "Welcome text opened"),
    ],
  },
  {
    id: "fan_darnell",
    artistId: ARTIST_ID,
    firstName: "Darnell",
    lastName: "Price",
    phone: "2145550194",
    email: "dprice@gmail.com",
    city: "Dallas",
    favoriteSong: "Ratchet",
    birthday: "",
    joinedAt: "2026-05-22T18:40:00",
    source: "QR code",
    tags: ["Dallas", "Show attendee"],
    notes: "",
    lastContactedAt: "2026-05-22T19:00:00",
    engagement: [
      ev("e10", "2026-05-22T18:40:00", "signup", "QR at pop-up"),
      ev("e11", "2026-05-22T19:00:00", "text", "Welcome text"),
    ],
  },
  {
    id: "fan_jasmine",
    artistId: ARTIST_ID,
    firstName: "Jasmine",
    lastName: "Reed",
    phone: "5045550177",
    email: "",
    city: "New Orleans",
    favoriteSong: "Nobody",
    birthday: "1999-08-30",
    joinedAt: "2026-08-24T23:50:00",
    source: "Live show",
    tags: ["New Orleans", "Show attendee"],
    notes: "Came with three friends. Capture them next time.",
    lastContactedAt: "",
    fromLastShow: true,
    engagement: [ev("e12", "2026-08-24T23:50:00", "signup", "Joined at Republic NOLA")],
  },
  {
    id: "fan_tyrell",
    artistId: ARTIST_ID,
    firstName: "Tyrell",
    lastName: "Grant",
    phone: "4045550112",
    email: "tyrellg@gmail.com",
    city: "Atlanta",
    favoriteSong: "Casamigo",
    birthday: "",
    joinedAt: "2026-08-12T11:22:00",
    source: "Website",
    tags: ["Atlanta"],
    notes: "Asked for the next video.",
    lastContactedAt: "2026-08-12T12:00:00",
    engagement: [
      ev("e13", "2026-08-12T11:22:00", "signup", "Website inner circle"),
      ev("e14", "2026-08-12T12:00:00", "email", "Opened Nobody teaser"),
    ],
  },
  {
    id: "fan_nia",
    artistId: ARTIST_ID,
    firstName: "Nia",
    lastName: "Cooper",
    phone: "5045550108",
    email: "nia.cooper@gmail.com",
    city: "New Orleans",
    favoriteSong: "Pretty Gremlin",
    birthday: "1996-03-08",
    joinedAt: "2025-12-14T16:00:00",
    source: "Referral",
    tags: ["Superfan", "New Orleans", "VIP", "Merch buyer"],
    notes: "Day-one. Brings people every show. Comp her Saturday.",
    lastContactedAt: "2026-08-20T15:10:00",
    engagement: [
      ev("e15", "2025-12-14T16:00:00", "signup", "Referred by Camille"),
      ev("e16", "2026-04-02T20:00:00", "show", "Tipitina's"),
      ev("e17", "2026-08-20T15:10:00", "text", "Sent exclusive snippet"),
      ev("e18", "2026-08-21T09:00:00", "merch", "Bought two tees"),
    ],
  },
  {
    id: "fan_brandon",
    artistId: ARTIST_ID,
    firstName: "Brandon",
    lastName: "Hale",
    phone: "",
    email: "brandon.hale@outlook.com",
    city: "Houston",
    favoriteSong: "Ratchet",
    birthday: "",
    joinedAt: "2026-08-08T21:40:00",
    source: "Live show",
    tags: ["Houston", "Show attendee"],
    notes: "No phone — get it at the next Houston date.",
    lastContactedAt: "2026-08-09T09:30:00",
    engagement: [
      ev("e19", "2026-08-08T21:40:00", "signup", "House of Blues"),
      ev("e20", "2026-08-09T09:30:00", "email", "Welcome email"),
    ],
  },
  {
    id: "fan_imani",
    artistId: ARTIST_ID,
    firstName: "Imani",
    lastName: "Cole",
    phone: "4045550166",
    email: "imanicole@gmail.com",
    city: "Atlanta",
    favoriteSong: "Nobody",
    birthday: "2000-07-21",
    joinedAt: "2026-07-02T13:18:00",
    source: "Instagram",
    tags: ["Atlanta", "Merch buyer"],
    notes: "",
    lastContactedAt: "2026-07-19T11:00:00",
    engagement: [
      ev("e21", "2026-07-02T13:18:00", "signup", "IG reel link"),
      ev("e22", "2026-07-18T21:00:00", "show", "The Loft"),
      ev("e23", "2026-07-19T11:00:00", "merch", "Signed poster"),
    ],
  },
  {
    id: "fan_chris",
    artistId: ARTIST_ID,
    firstName: "Chris",
    lastName: "Nguyen",
    phone: "2145550133",
    email: "cnguyen@gmail.com",
    city: "Dallas",
    favoriteSong: "Pretty Gremlin",
    birthday: "",
    joinedAt: "2026-06-28T19:05:00",
    source: "TikTok",
    tags: ["Dallas"],
    notes: "",
    lastContactedAt: "",
    engagement: [ev("e24", "2026-06-28T19:05:00", "signup", "For You page")],
  },
  {
    id: "fan_sasha",
    artistId: ARTIST_ID,
    firstName: "Sasha",
    lastName: "Pierre",
    phone: "5045550190",
    email: "sasha.pierre@gmail.com",
    city: "New Orleans",
    favoriteSong: "Ratchet",
    birthday: "1997-09-04",
    joinedAt: "2026-08-24T23:33:00",
    source: "Live show",
    tags: ["VIP", "New Orleans", "Show attendee"],
    notes: "Promoter's cousin. Treat like family.",
    lastContactedAt: "",
    fromLastShow: true,
    engagement: [ev("e25", "2026-08-24T23:33:00", "signup", "Republic NOLA VIP")],
  },
  {
    id: "fan_andre",
    artistId: ARTIST_ID,
    firstName: "Andre",
    lastName: "Sims",
    phone: "4045550120",
    email: "andresims@gmail.com",
    city: "Atlanta",
    favoriteSong: "Ratchet",
    birthday: "",
    joinedAt: "2026-08-21T17:44:00",
    source: "QR code",
    tags: ["Atlanta"],
    notes: "",
    lastContactedAt: "2026-08-21T18:00:00",
    engagement: [
      ev("e26", "2026-08-21T17:44:00", "signup", "QR at the studio"),
      ev("e27", "2026-08-21T18:00:00", "text", "Welcome text"),
    ],
  },
  {
    id: "fan_maya",
    artistId: ARTIST_ID,
    firstName: "Maya",
    lastName: "Fontenot",
    phone: "3375550181",
    email: "maya.fontenot@gmail.com",
    city: "Lafayette",
    favoriteSong: "Pretty Gremlin",
    birthday: "1995-12-01",
    joinedAt: "2026-04-11T08:22:00",
    source: "Website",
    tags: ["Superfan"],
    notes: "Drives in from Lafayette for every NOLA show.",
    lastContactedAt: "2026-08-10T16:00:00",
    engagement: [
      ev("e28", "2026-04-11T08:22:00", "signup", "Website"),
      ev("e29", "2026-08-10T16:00:00", "email", "Opened 5 Signs letter"),
    ],
  },
  {
    id: "fan_malik",
    artistId: ARTIST_ID,
    firstName: "Malik",
    lastName: "Rivers",
    phone: "7135550144",
    email: "",
    city: "Houston",
    favoriteSong: "Nobody",
    birthday: "",
    joinedAt: "2026-08-08T22:30:00",
    source: "Live show",
    tags: ["Houston", "Show attendee"],
    notes: "",
    lastContactedAt: "",
    engagement: [ev("e30", "2026-08-08T22:30:00", "signup", "House of Blues")],
  },
  {
    id: "fan_tiana",
    artistId: ARTIST_ID,
    firstName: "Tiana",
    lastName: "Brooks",
    phone: "4045550171",
    email: "tiana.b@icloud.com",
    city: "Atlanta",
    favoriteSong: "Casamigo",
    birthday: "2002-02-14",
    joinedAt: "2026-08-16T20:12:00",
    source: "Instagram",
    tags: ["Atlanta", "Superfan"],
    notes: "Wants Nobody first. Put her on the exclusive list.",
    lastContactedAt: "2026-08-17T10:00:00",
    engagement: [
      ev("e31", "2026-08-16T20:12:00", "signup", "IG live comment"),
      ev("e32", "2026-08-17T10:00:00", "text", "Sent unreleased 15s"),
      ev("e33", "2026-08-17T10:04:00", "click", "Played snippet 6 times"),
    ],
  },
  {
    id: "fan_jaylen",
    artistId: ARTIST_ID,
    firstName: "Jaylen",
    lastName: "Scott",
    phone: "2145550155",
    email: "jaylens@gmail.com",
    city: "Dallas",
    favoriteSong: "Ratchet",
    birthday: "",
    joinedAt: "2026-03-09T12:00:00",
    source: "Other",
    tags: ["Dallas"],
    notes: "Met at a radio drop-in.",
    lastContactedAt: "2026-03-10T09:00:00",
    engagement: [
      ev("e34", "2026-03-09T12:00:00", "signup", "Radio lounge"),
      ev("e35", "2026-03-10T09:00:00", "email", "Welcome"),
    ],
  },
  {
    id: "fan_camille",
    artistId: ARTIST_ID,
    firstName: "Camille",
    lastName: "Doucet",
    phone: "5045550129",
    email: "camilledoucet@gmail.com",
    city: "New Orleans",
    favoriteSong: "Nobody",
    birthday: "1993-06-16",
    joinedAt: "2026-08-24T23:58:00",
    source: "Live show",
    tags: ["New Orleans", "Show attendee", "Referral"],
    notes: "Brought Nia originally. Circle is closing.",
    lastContactedAt: "",
    fromLastShow: true,
    engagement: [ev("e36", "2026-08-24T23:58:00", "signup", "Republic NOLA")],
  },
  {
    id: "fan_rico",
    artistId: ARTIST_ID,
    firstName: "Rico",
    lastName: "Bennett",
    phone: "4045550199",
    email: "rico.b@gmail.com",
    city: "Atlanta",
    favoriteSong: "Ratchet",
    birthday: "",
    joinedAt: "2026-07-22T15:40:00",
    source: "Referral",
    tags: ["Atlanta"],
    notes: "",
    lastContactedAt: "2026-07-22T16:00:00",
    engagement: [ev("e37", "2026-07-22T15:40:00", "signup", "Referred by Marcus")],
  },
  {
    id: "fan_destiny",
    artistId: ARTIST_ID,
    firstName: "Destiny",
    lastName: "Hall",
    phone: "7135550187",
    email: "destinyhall@gmail.com",
    city: "Houston",
    favoriteSong: "Pretty Gremlin",
    birthday: "1998-10-10",
    joinedAt: "2026-05-01T21:00:00",
    source: "TikTok",
    tags: ["Houston", "Merch buyer"],
    notes: "",
    lastContactedAt: "2026-05-04T12:00:00",
    engagement: [
      ev("e38", "2026-05-01T21:00:00", "signup", "TikTok"),
      ev("e39", "2026-05-04T12:00:00", "merch", "Ordered tank"),
    ],
  },
  {
    id: "fan_omar",
    artistId: ARTIST_ID,
    firstName: "Omar",
    lastName: "Jackson",
    phone: "5045550152",
    email: "omarj@gmail.com",
    city: "New Orleans",
    favoriteSong: "Ratchet",
    birthday: "",
    joinedAt: "2026-08-19T19:20:00",
    source: "QR code",
    tags: ["New Orleans"],
    notes: "",
    lastContactedAt: "2026-08-19T19:30:00",
    engagement: [ev("e40", "2026-08-19T19:20:00", "signup", "QR at the studio")],
  },
  {
    id: "fan_brittany",
    artistId: ARTIST_ID,
    firstName: "Brittany",
    lastName: "Kane",
    phone: "4045550148",
    email: "bkane@gmail.com",
    city: "Atlanta",
    favoriteSong: "Nobody",
    birthday: "",
    joinedAt: "2026-07-18T22:12:00",
    source: "Live show",
    tags: ["Atlanta", "Show attendee"],
    notes: "Coming back Saturday.",
    lastContactedAt: "2026-08-22T14:00:00",
    engagement: [
      ev("e41", "2026-07-18T22:12:00", "signup", "The Loft"),
      ev("e42", "2026-08-22T14:00:00", "text", "Saturday reminder draft"),
    ],
  },
  {
    id: "fan_eli",
    artistId: ARTIST_ID,
    firstName: "Eli",
    lastName: "Thomas",
    phone: "5045550163",
    email: "",
    city: "New Orleans",
    favoriteSong: "Pretty Gremlin",
    birthday: "2003-05-05",
    joinedAt: "2026-08-24T23:47:00",
    source: "Live show",
    tags: ["New Orleans", "Show attendee"],
    notes: "Young. Keep the texts clean.",
    lastContactedAt: "",
    fromLastShow: true,
    engagement: [ev("e43", "2026-08-24T23:47:00", "signup", "Republic NOLA")],
  },
];

export const releases: Release[] = [
  {
    id: "rel_fivesigns",
    artistId: ARTIST_ID,
    title: "5 Signs of a Fake B",
    status: "released",
    releaseDate: "2026-07-04",
    cover: "/covers/five-signs.jpg",
    spotify: "https://open.spotify.com/artist/31FeTRg0UrwKHhHREE6ige",
    apple: "https://music.apple.com/us/album/5-signs-of-a-fake-b/6787486979",
    youtube: "https://youtube.com/@dejavulivetv",
    streams: 412800,
    saves: 28110,
    playlistAdds: 164,
  },
  {
    id: "rel_nobody",
    artistId: ARTIST_ID,
    title: "Nobody",
    status: "released",
    releaseDate: "2026-05-16",
    cover: "/covers/nobody.jpg",
    spotify: "https://open.spotify.com/artist/31FeTRg0UrwKHhHREE6ige",
    apple: "https://music.apple.com/us/artist/deja-vu-504/1438031169",
    youtube: "https://youtube.com/@dejavulivetv",
    streams: 312800,
    saves: 22110,
    playlistAdds: 140,
  },
  {
    id: "rel_ratchet",
    artistId: ARTIST_ID,
    title: "Ratchet",
    status: "released",
    releaseDate: "2026-03-28",
    cover: "/covers/ratchet.jpg",
    spotify: "https://open.spotify.com/artist/31FeTRg0UrwKHhHREE6ige",
    apple: "https://music.apple.com/us/artist/deja-vu-504/1438031169",
    youtube: "https://youtube.com/@dejavulivetv",
    streams: 184200,
    saves: 12440,
    playlistAdds: 86,
  },
  {
    id: "rel_gremlin",
    artistId: ARTIST_ID,
    title: "Pretty Gremlin",
    status: "released",
    releaseDate: "2026-02-14",
    cover: "/covers/pretty-gremlin.jpg",
    spotify: "https://open.spotify.com/artist/31FeTRg0UrwKHhHREE6ige",
    apple: "https://music.apple.com/us/artist/deja-vu-504/1438031169",
    youtube: "https://youtube.com/@dejavulivetv",
    streams: 96400,
    saves: 6102,
    playlistAdds: 41,
  },
  {
    id: "rel_casamigo",
    artistId: ARTIST_ID,
    title: "Casamigo",
    status: "released",
    releaseDate: "2025-11-21",
    cover: "/covers/casamigo.jpg",
    spotify: "https://open.spotify.com/artist/31FeTRg0UrwKHhHREE6ige",
    apple: "https://music.apple.com/us/artist/deja-vu-504/1438031169",
    youtube: "https://youtube.com/@dejavulivetv",
    streams: 72800,
    saves: 4890,
    playlistAdds: 33,
  },
];

export const shows: Show[] = [
  {
    id: "show_atl_sat",
    artistId: ARTIST_ID,
    venue: "Center Stage",
    city: "Atlanta",
    date: "2026-08-29",
    time: "10:00 PM",
    expectedAttendance: 220,
    actualAttendance: 0,
    status: "upcoming",
    fansCaptured: 0,
    notes: "Dre confirmed guest list 20. Soundcheck 6:30.",
  },
  {
    id: "show_hou_sep",
    artistId: ARTIST_ID,
    venue: "Warehouse Live",
    city: "Houston",
    date: "2026-09-12",
    time: "9:30 PM",
    expectedAttendance: 300,
    actualAttendance: 0,
    status: "upcoming",
    fansCaptured: 0,
    notes: "",
  },
  {
    id: "show_dal_sep",
    artistId: ARTIST_ID,
    venue: "Trees",
    city: "Dallas",
    date: "2026-09-26",
    time: "10:00 PM",
    expectedAttendance: 250,
    actualAttendance: 0,
    status: "upcoming",
    fansCaptured: 0,
    notes: "",
  },
  {
    id: "show_nola_republic",
    artistId: ARTIST_ID,
    venue: "Republic NOLA",
    city: "New Orleans",
    date: "2026-08-24",
    time: "11:00 PM",
    expectedAttendance: 160,
    actualAttendance: 180,
    status: "past",
    fansCaptured: 37,
    notes: "Room was over capacity. 37 new numbers. Text them today.",
  },
  {
    id: "show_hou_hob",
    artistId: ARTIST_ID,
    venue: "House of Blues",
    city: "Houston",
    date: "2026-08-08",
    time: "9:00 PM",
    expectedAttendance: 280,
    actualAttendance: 240,
    status: "past",
    fansCaptured: 22,
    notes: "",
  },
  {
    id: "show_atl_loft",
    artistId: ARTIST_ID,
    venue: "The Loft",
    city: "Atlanta",
    date: "2026-07-18",
    time: "10:00 PM",
    expectedAttendance: 200,
    actualAttendance: 190,
    status: "past",
    fansCaptured: 28,
    notes: "",
  },
];

export const money: MoneyEntry[] = [
  { id: "m1", artistId: ARTIST_ID, kind: "income", category: "Shows", amount: 2400, date: "2026-08-24", note: "Republic NOLA door + tips" },
  { id: "m2", artistId: ARTIST_ID, kind: "income", category: "Shows", amount: 3200, date: "2026-08-08", note: "House of Blues guarantee" },
  { id: "m3", artistId: ARTIST_ID, kind: "income", category: "Shows", amount: 2800, date: "2026-07-18", note: "The Loft" },
  { id: "m4", artistId: ARTIST_ID, kind: "income", category: "Shows", amount: 10000, date: "2026-06-01", note: "Spring run (4 rooms)" },
  { id: "m5", artistId: ARTIST_ID, kind: "income", category: "Merch", amount: 1860, date: "2026-08-24", note: "Republic NOLA table" },
  { id: "m6", artistId: ARTIST_ID, kind: "income", category: "Merch", amount: 1440, date: "2026-08-08", note: "Houston table" },
  { id: "m7", artistId: ARTIST_ID, kind: "income", category: "Merch", amount: 2940, date: "2026-07-01", note: "Online restock" },
  { id: "m8", artistId: ARTIST_ID, kind: "income", category: "Streaming", amount: 2180, date: "2026-08-01", note: "Q2–Q3 payouts" },
  { id: "m9", artistId: ARTIST_ID, kind: "income", category: "Features", amount: 1500, date: "2026-06-20", note: "Bounce remix hook" },
  { id: "m10", artistId: ARTIST_ID, kind: "income", category: "Features", amount: 2000, date: "2026-04-04", note: "Hook for a 504 collab" },
  { id: "m11", artistId: ARTIST_ID, kind: "income", category: "Sponsorships", amount: 1200, date: "2026-07-12", note: "Local rum brand IG" },
  { id: "m12", artistId: ARTIST_ID, kind: "income", category: "Other", amount: 450, date: "2026-05-18", note: "Session vocal" },
  { id: "m13", artistId: ARTIST_ID, kind: "expense", category: "Studio", amount: 2800, date: "2026-08-15", note: "Nobody radio edit + vocals" },
  { id: "m14", artistId: ARTIST_ID, kind: "expense", category: "Travel", amount: 1640, date: "2026-08-07", note: "Houston run" },
  { id: "m15", artistId: ARTIST_ID, kind: "expense", category: "Ads", amount: 890, date: "2026-08-01", note: "IG + TikTok boosts" },
  { id: "m16", artistId: ARTIST_ID, kind: "expense", category: "Photoshoot", amount: 750, date: "2026-07-29", note: "Lena Park session" },
  { id: "m17", artistId: ARTIST_ID, kind: "expense", category: "Other", amount: 320, date: "2026-08-20", note: "Hair + wardrobe" },
];

export const team: TeamMember[] = [
  {
    id: "tm_bigga",
    artistId: ARTIST_ID,
    name: "Bigga Rankin Management",
    role: "Management",
    phone: "5045550140",
    email: "dejavu504bookings@gmail.com",
    notes: "Booking and management office. Use the inbox. Long live OG.",
    followUp: "",
  },
  {
    id: "tm_maya",
    artistId: ARTIST_ID,
    name: "Maya Chen",
    role: "Day-to-day",
    phone: "4045550101",
    email: "maya@mayachen.co",
    notes: "Protects the calendar. Wants Atlanta locked and 5 Signs still working the South.",
    followUp: "Send her last night's recap.",
  },
  {
    id: "tm_rico",
    artistId: ARTIST_ID,
    name: "Rico Bell",
    role: "Producer",
    phone: "5045550102",
    email: "rico@bellsound.studio",
    notes: "Nobody radio edit is in his room. Mix notes due Thursday.",
    followUp: "Approve the 0:42 downbeat change.",
  },
  {
    id: "tm_slide",
    artistId: ARTIST_ID,
    name: "DJ Slide",
    role: "DJ",
    phone: "4045550103",
    email: "slide@gmail.com",
    notes: "Opens Atlanta. Has the Ratchet bounce remix.",
    followUp: "",
  },
  {
    id: "tm_lena",
    artistId: ARTIST_ID,
    name: "Lena Park",
    role: "Photographer",
    phone: "4045550104",
    email: "hello@lenapark.studio",
    notes: "Shot the 5 Signs stills. Selects in drive.",
    followUp: "Pick 6 for the keep-pushing campaign.",
  },
  {
    id: "tm_chris",
    artistId: ARTIST_ID,
    name: "Chris Vale",
    role: "Videographer",
    phone: "7135550105",
    email: "chris@valefilm.co",
    notes: "Has the Republic NOLA recap clips. 4 usable 15s cuts.",
    followUp: "Ask for the color-graded encore clip today.",
  },
  {
    id: "tm_dre",
    artistId: ARTIST_ID,
    name: "Dre Lewis",
    role: "Promoter",
    phone: "4045550106",
    email: "dre@lotatl.com",
    notes: "Atlanta Saturday. Guest list cap 20.",
    followUp: "Confirm Saturday guest list and door time.",
  },
  {
    id: "tm_lot",
    artistId: ARTIST_ID,
    name: "The Lot Booking",
    role: "Booking",
    phone: "4045550107",
    email: "dejavu504bookings@gmail.com",
    notes: "Holding Oct Miami and Nov Charlotte.",
    followUp: "",
  },
  {
    id: "tm_simone",
    artistId: ARTIST_ID,
    name: "Simone Hart",
    role: "Marketing",
    phone: "5045550108",
    email: "simone@hartstudio.co",
    notes: "Captions and TikTok sequencing. Don't let her over-polish the 504 voice.",
    followUp: "",
  },
];

export const activity: ActivityItem[] = [
  {
    id: "a1",
    artistId: ARTIST_ID,
    at: "2026-08-25T09:10:00",
    title: "37 new fans from Republic NOLA",
    detail: "Last night's room. None of them have been texted yet.",
    type: "fan",
  },
  {
    id: "a2",
    artistId: ARTIST_ID,
    at: "2026-08-25T08:40:00",
    title: "Encore clip is ready",
    detail: "Chris Vale dropped 4 cuts from last night.",
    type: "content",
  },
  {
    id: "a3",
    artistId: ARTIST_ID,
    at: "2026-08-24T23:20:00",
    title: "Republic NOLA sold past the number",
    detail: "180 in a 160 room. Energy was high.",
    type: "show",
  },
  {
    id: "a4",
    artistId: ARTIST_ID,
    at: "2026-08-24T18:00:00",
    title: "Nobody radio edit pending one change",
    detail: "Rico wants a call on the 0:42 downbeat.",
    type: "music",
  },
  {
    id: "a5",
    artistId: ARTIST_ID,
    at: "2026-08-23T16:12:00",
    title: "Dre confirmed Atlanta",
    detail: "Center Stage Saturday. Guest list 20.",
    type: "team",
  },
  {
    id: "a6",
    artistId: ARTIST_ID,
    at: "2026-08-22T12:00:00",
    title: "Merch restock moving",
    detail: "14 tees sold online this week.",
    type: "money",
  },
];

export const LAST_NIGHT_UNTEXTED = 37;

export const FAN_TAGS = [
  "VIP",
  "Superfan",
  "Atlanta",
  "New Orleans",
  "Houston",
  "Dallas",
  "Show attendee",
  "Merch buyer",
];

export const FAN_SOURCES: Fan["source"][] = [
  "Live show",
  "Instagram",
  "TikTok",
  "QR code",
  "Website",
  "Referral",
  "Other",
];
