/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as CreateRouteImport } from './routes/create'
import { Route as FansRouteImport } from './routes/fans'
import { Route as FollowUpRouteImport } from './routes/follow-up'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MoneyRouteImport } from './routes/money'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MusicRouteImport } from './routes/music'
import { Route as NextRouteImport } from './routes/next'
import { Route as PressRouteImport } from './routes/press'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShowModeRouteImport } from './routes/show-mode'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as TeamRouteImport } from './routes/team'
import { Route as FansFanIdRouteImport } from './routes/fans.$fanId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const FansRoute = FansRouteImport.update({
  id: '/fans',
  path: '/fans',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpRoute = FollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyRoute = MoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const NextRoute = NextRouteImport.update({
  id: '/next',
  path: '/next',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowModeRoute = ShowModeRouteImport.update({
  id: '/show-mode',
  path: '/show-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const FansFanIdRoute = FansFanIdRouteImport.update({
  id: '/$fanId',
  path: '/$fanId',
  getParentRoute: () => FansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/brand': typeof BrandRoute
  '/capture': typeof CaptureRoute
  '/create': typeof CreateRoute
  '/fans': typeof FansRouteWithChildren
  '/follow-up': typeof FollowUpRoute
  '/join': typeof JoinRoute
  '/money': typeof MoneyRoute
  '/more': typeof MoreRoute
  '/music': typeof MusicRoute
  '/next': typeof NextRoute
  '/press': typeof PressRoute
  '/settings': typeof SettingsRoute
  '/show-mode': typeof ShowModeRoute
  '/shows': typeof ShowsRoute
  '/team': typeof TeamRoute
  '/fans/$fanId': typeof FansFanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/brand': typeof BrandRoute
  '/capture': typeof CaptureRoute
  '/create': typeof CreateRoute
  '/fans': typeof FansRouteWithChildren
  '/follow-up': typeof FollowUpRoute
  '/join': typeof JoinRoute
  '/money': typeof MoneyRoute
  '/more': typeof MoreRoute
  '/music': typeof MusicRoute
  '/next': typeof NextRoute
  '/press': typeof PressRoute
  '/settings': typeof SettingsRoute
  '/show-mode': typeof ShowModeRoute
  '/shows': typeof ShowsRoute
  '/team': typeof TeamRoute
  '/fans/$fanId': typeof FansFanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/brand': typeof BrandRoute
  '/capture': typeof CaptureRoute
  '/create': typeof CreateRoute
  '/fans': typeof FansRouteWithChildren
  '/follow-up': typeof FollowUpRoute
  '/join': typeof JoinRoute
  '/money': typeof MoneyRoute
  '/more': typeof MoreRoute
  '/music': typeof MusicRoute
  '/next': typeof NextRoute
  '/press': typeof PressRoute
  '/settings': typeof SettingsRoute
  '/show-mode': typeof ShowModeRoute
  '/shows': typeof ShowsRoute
  '/team': typeof TeamRoute
  '/fans/$fanId': typeof FansFanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/brand'
    | '/capture'
    | '/create'
    | '/fans'
    | '/follow-up'
    | '/join'
    | '/money'
    | '/more'
    | '/music'
    | '/next'
    | '/press'
    | '/settings'
    | '/show-mode'
    | '/shows'
    | '/team'
    | '/fans/$fanId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/brand'
    | '/capture'
    | '/create'
    | '/fans'
    | '/follow-up'
    | '/join'
    | '/money'
    | '/more'
    | '/music'
    | '/next'
    | '/press'
    | '/settings'
    | '/show-mode'
    | '/shows'
    | '/team'
    | '/fans/$fanId'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/brand'
    | '/capture'
    | '/create'
    | '/fans'
    | '/follow-up'
    | '/join'
    | '/money'
    | '/more'
    | '/music'
    | '/next'
    | '/press'
    | '/settings'
    | '/show-mode'
    | '/shows'
    | '/team'
    | '/fans/$fanId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  BrandRoute: typeof BrandRoute
  CaptureRoute: typeof CaptureRoute
  CreateRoute: typeof CreateRoute
  FansRoute: typeof FansRouteWithChildren
  FollowUpRoute: typeof FollowUpRoute
  JoinRoute: typeof JoinRoute
  MoneyRoute: typeof MoneyRoute
  MoreRoute: typeof MoreRoute
  MusicRoute: typeof MusicRoute
  NextRoute: typeof NextRoute
  PressRoute: typeof PressRoute
  SettingsRoute: typeof SettingsRoute
  ShowModeRoute: typeof ShowModeRoute
  ShowsRoute: typeof ShowsRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fans': {
      id: '/fans'
      path: '/fans'
      fullPath: '/fans'
      preLoaderRoute: typeof FansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-up': {
      id: '/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof FollowUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money': {
      id: '/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof MoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next': {
      id: '/next'
      path: '/next'
      fullPath: '/next'
      preLoaderRoute: typeof NextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show-mode': {
      id: '/show-mode'
      path: '/show-mode'
      fullPath: '/show-mode'
      preLoaderRoute: typeof ShowModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fans/$fanId': {
      id: '/fans/$fanId'
      path: '/$fanId'
      fullPath: '/fans/$fanId'
      preLoaderRoute: typeof FansFanIdRouteImport
      parentRoute: typeof FansRoute
    }
  }
}

interface FansRouteChildren {
  FansFanIdRoute: typeof FansFanIdRoute
}

const FansRouteChildren: FansRouteChildren = {
  FansFanIdRoute: FansFanIdRoute,
}

const FansRouteWithChildren = FansRoute._addFileChildren(FansRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  BrandRoute: BrandRoute,
  CaptureRoute: CaptureRoute,
  CreateRoute: CreateRoute,
  FansRoute: FansRouteWithChildren,
  FollowUpRoute: FollowUpRoute,
  JoinRoute: JoinRoute,
  MoneyRoute: MoneyRoute,
  MoreRoute: MoreRoute,
  MusicRoute: MusicRoute,
  NextRoute: NextRoute,
  PressRoute: PressRoute,
  SettingsRoute: SettingsRoute,
  ShowModeRoute: ShowModeRoute,
  ShowsRoute: ShowsRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
